----Снижаем урон газовым гранатам
--Citizen.CreateThread(function()
--    while true do
--	Citizen.Wait(0)
--	N_0x4757f00bc6323cfe(GetHashKey("weapon_smokegrenade"), 0.1)
--	N_0x4757f00bc6323cfe(GetHashKey("weapon_bzgas"), 0.1)
--    end
--end)
--
--
--local tiempo = 15000 -- in miliseconds >> 1000 ms = 1s
--Citizen.CreateThread(function()
--	while true do
--		Citizen.Wait(0)
--		if IsPedBeingStunned(GetPlayerPed(-1)) then
--		SetPedMinGroundTimeForStungun(GetPlayerPed(-1), tiempo)
--		end
--	end
--end)